Repository canonical/k8s-snap, pull requests merged in 2025-03, with the labels that each got.

#1143 docs: remove 1.31 release notes
  docs/canonicalk8s/snap/reference/releases.md
  docs/canonicalk8s/snap/reference/versions/1.31.md
  docs/canonicalk8s/snap/reference/versions/1.32.md
Labels: backport release-1.32

#1095 build: bump coredns chart to 1.36.2, image to 1.11.4-ck1
  build-scripts/hack/update-coredns-chart.sh
  k8s/manifests/charts/coredns-1.36.0.tgz
  k8s/manifests/charts/coredns-1.36.2.tgz
  src/k8s/pkg/k8sd/features/coredns/chart.go
Labels: dependencies

#1112 build: bump CSI image versions
  src/k8s/pkg/k8sd/features/localpv/chart.go
Labels: dependencies

#1164 fix: Temporarily disable snap/k8sd config sync during snap upgrade
  snap/hooks/post-refresh
  snap/hooks/pre-refresh
Labels: backport release-1.32

#1171 ci: Run all tests on Kubernetes component / feature updates
  .github/workflows/lint_and_integration.yaml
Labels: backport release-1.32, backport release-1.31

#1194 docs: fix broken link issue #1187
  docs/canonicalk8s/snap/explanation/load-balancer.md
Labels: backport release-1.32

#1201 ci: markdown lint calculate changed files through git
  .github/workflows/markdown.yaml
Labels: backport, backport release-1.32, backport release-1.31

#1205 fix: Move snapd sync to custom post-refresh hook
  snap/hooks/post-refresh
  src/k8s/pkg/k8sd/app/hooks_post_refresh.go
  src/k8s/pkg/k8sd/app/hooks_start.go
  src/k8s/pkg/snap/interface.go
  src/k8s/pkg/snap/mock/mock.go
  src/k8s/pkg/snap/snap.go
Labels: backport release-1.32

#1239 fix: snap refreshes on worker nodes
  src/k8s/cmd/k8s/k8s_x_snapd_config.go
Labels: backport release-1.32, backport release-1.31

#1125 test: Adds Sonobuoy CNCF e2e nigthly tests
  .github/workflows/e2e-tests.yaml
  .github/workflows/nightly-test.yaml
  tests/integration/tests/test_cncf_conformace.py
  tests/integration/tests/test_util/tags.py
  tests/integration/tests/test_util/util.py
Labels: backport release-1.32
