Repository canonical/k8s-snap, pull requests merged in 2025-08, with the labels that each got.

#1713 fix: Include control-plane-taints in the k8sd configmap
  src/k8s/pkg/k8sd/types/cluster_config_kubelet.go
  src/k8s/pkg/k8sd/types/cluster_config_kubelet_test.go
Labels: backport release-1.32, backport release-1.33

#1697 docs: Add node removal notice
  docs/canonicalk8s/snap/explanation/high-availability.md
  docs/canonicalk8s/snap/howto/install/uninstall.md
  docs/canonicalk8s/snap/tutorial/add-remove-nodes.md
Labels: backport release-1.32, backport release-1.33

#1710 feat: Included managed-etcd service inspection
  docs/canonicalk8s/snap/reference/inspection-reports.md
  k8s/scripts/inspect.sh
Labels: backport release-1.32, backport release-1.33

#1730 fix: use v1.3.4 k8s-dqlite patch release
  build-scripts/components/k8s-dqlite/version
Labels: backport release-1.32

#1759 chore: add security-events to integration workflow
  .github/workflows/lint_and_integration.yaml
Labels: backport release-1.32, backport release-1.33

#1746 docs: CIS etcd updates
  docs/canonicalk8s/snap/howto/security/cis-assessment.md
Labels: backport release-1.32, backport release-1.33

#1711 docs: Replace k8s-dqlite with etcd
  docs/canonicalk8s/.sphinx/.wordlist.txt
  docs/canonicalk8s/assets/arch.dsl
  docs/canonicalk8s/assets/example-bootstrap-config.yaml
  docs/canonicalk8s/assets/k8s-container.puml
  docs/canonicalk8s/assets/k8sd-component.puml
  docs/canonicalk8s/capi/howto/troubleshooting.md
  docs/canonicalk8s/capi/reference/configs.md
  docs/canonicalk8s/charm/howto/etcd.md
  docs/canonicalk8s/charm/howto/install/install-custom.md
  docs/canonicalk8s/charm/howto/troubleshooting.md
  docs/canonicalk8s/snap/explanation/architecture.md
  docs/canonicalk8s/snap/explanation/clustering.md
  docs/canonicalk8s/snap/explanation/security/crypto.md
  docs/canonicalk8s/snap/howto/external-datastore.md
  docs/canonicalk8s/snap/howto/security/refresh-certs.md
  docs/canonicalk8s/snap/howto/troubleshooting.md
  docs/canonicalk8s/snap/reference/architecture.md
  docs/canonicalk8s/snap/reference/certificates.md
  docs/canonicalk8s/snap/reference/dqlite.md
  docs/canonicalk8s/snap/reference/etcd.md
  docs/canonicalk8s/snap/reference/index.md
  docs/canonicalk8s/snap/reference/inspection-reports.md
  docs/canonicalk8s/snap/reference/ports-and-services.md
Labels: backport release-1.32, backport release-1.33

#1781 feat: Trigger feature controller on k8sd startup
  src/k8s/pkg/k8sd/app/hooks_start.go
Labels: backport release-1.32, backport release-1.33

#1731 docs: UX adjustments around blocked units on bootstrap change prevention
  docs/canonicalk8s/charm/reference/troubleshooting.md
Labels: backport release-1.33

#1787 docs: fix mistake in example intermediate ca Secret
  docs/canonicalk8s/capi/howto/intermediate-ca.md
Labels: backport release-1.32, backport release-1.33

#1766 docs(CAPI): Fix files field to represent an array
  docs/canonicalk8s/capi/reference/configs.md
Labels: backport release-1.32, backport release-1.33
