Repository canonical/k8s-snap, pull requests merged in 2025-06, with the labels that each got.

#1469 fix: move cleanup code to go and handle custom containerd path
  k8s/lib.sh
  k8s/profiles/containerd
  src/k8s/cmd/k8s/k8s_x_cleanup.go
  src/k8s/pkg/k8sd/app/hooks_remove.go
  src/k8s/pkg/k8sd/setup/containerd.go
  src/k8s/pkg/snap/interface.go
  src/k8s/pkg/snap/mock/mock.go
  src/k8s/pkg/snap/snap.go
  src/k8s/pkg/snap/util/cleanup/cleanup.go
  src/k8s/pkg/snap/util/cleanup/internal/containerd_paths.go
  src/k8s/pkg/snap/util/cleanup/internal/containerd_paths_test.go
  src/k8s/pkg/snap/util/cleanup/internal/containers.go
  src/k8s/pkg/snap/util/cleanup/internal/kube_proxy.go
  src/k8s/pkg/snap/util/cleanup/internal/loop_devices.go
  src/k8s/pkg/snap/util/cleanup/internal/loop_devices_test.go
  src/k8s/pkg/snap/util/cleanup/internal/network_namespaces.go
  src/k8s/pkg/snap/util/cleanup/internal/network_namespaces_test.go
  src/k8s/pkg/snap/util/cleanup/internal/plugins.go
  src/k8s/pkg/snap/util/cleanup/internal/plugins_test.go
  src/k8s/pkg/snap/util/cleanup/internal/volume_mounts.go
  src/k8s/pkg/snap/util/cleanup/internal/volume_mounts_test.go
  src/k8s/pkg/snap/util/containerd.go
  src/k8s/pkg/utils/mount/mock.go
  src/k8s/pkg/utils/mount/mount.go
  src/k8s/pkg/utils/mount/unix.go
  src/k8s/pkg/utils/netns/mock.go
  src/k8s/pkg/utils/netns/netns.go
  src/k8s/pkg/utils/netns/unix.go
Labels: backport release-1.32, backport release-1.33

#1500 fix: patch k8s to relax the timeouts for populating resource caches
  build-scripts/components/kubernetes/patches/default/0001-Increase-the-timeout-and-interval-for-populating-cac.patch
  build-scripts/components/kubernetes/patches/v1.32.0/0001-Increase-the-timeout-and-interval-for-populating-cac.patch
Labels: backport release-1.32, backport release-1.33

#1517 fix: address test_clustering flakiness
  tests/integration/tests/test_clustering.py
Labels: backport release-1.32, backport release-1.33

#1529 test: Fix annotation test
  .github/workflows/lint_and_integration.yaml
  tests/integration/tests/test_annotations.py
Labels: backport release-1.32, backport release-1.33

#1546 fix: Don't print k8s binary outputs in CLI
  src/k8s/pkg/snap/snap.go
Labels: backport release-1.32, backport release-1.33

#1577 fix: add retry to get_join_token helper
  tests/integration/tests/test_util/util.py
Labels: backport release-1.32, backport release-1.33

#1565 docs: update the ports and services page for DISA PPS
  docs/canonicalk8s/snap/howto/security/disa-stig-assessment.md
  docs/canonicalk8s/snap/reference/ports-and-services.md
Labels: backport release-1.32, backport release-1.33

#1600 docs: Update custom worker join how to guide
  docs/canonicalk8s/conf.py
  docs/canonicalk8s/snap/howto/install/custom-worker.md
Labels: backport release-1.32, backport release-1.31, backport release-1.33

#1603 docs: document Auto Namespace creation and RBD disable
  docs/canonicalk8s/charm/howto/ceph-csi.md
Labels: backport release-1.33
