Repository canonical/k8s-snap, pull requests merged in 2025-04, with the labels that each got.

#1228 fix: Execute post-refresh hook after node is ready
  src/k8s/pkg/k8sd/app/app.go
  src/k8s/pkg/k8sd/app/hooks_node_ready.go
  src/k8s/pkg/k8sd/app/hooks_post_refresh.go
  src/k8s/pkg/k8sd/app/hooks_remove.go
  src/k8s/pkg/k8sd/app/hooks_start.go
  tests/integration/tests/test_airgapped.py
  tests/integration/tests/test_annotations.py
  tests/integration/tests/test_clustering_race.py
  tests/integration/tests/test_loadbalancer.py
  tests/integration/tests/test_strict_interfaces.py
  tests/integration/tests/test_util/util.py
Labels: backport release-1.32

#1262 fix: Don't wait for services to terminate on removed node
  src/k8s/pkg/k8sd/api/certificates_refresh.go
  src/k8s/pkg/k8sd/api/certificates_update.go
  src/k8s/pkg/k8sd/app/hooks_remove.go
  src/k8s/pkg/k8sd/controllers/control_plane_configuration.go
  src/k8s/pkg/k8sd/controllers/control_plane_configuration_test.go
  src/k8s/pkg/k8sd/controllers/node_configuration.go
  src/k8s/pkg/k8sd/controllers/node_configuration_test.go
  src/k8s/pkg/k8sd/controllers/node_label.go
  src/k8s/pkg/k8sd/controllers/node_label_test.go
  src/k8s/pkg/snap/interface.go
  src/k8s/pkg/snap/mock/mock.go
  src/k8s/pkg/snap/pebble.go
  src/k8s/pkg/snap/pebble_test.go
  src/k8s/pkg/snap/snap.go
  src/k8s/pkg/snap/snap_test.go
  src/k8s/pkg/snap/util/services.go
  src/k8s/pkg/snap/util/services_test.go
  tests/integration/tests/test_clustering_race.py
Labels: backport release-1.32

#1185 test: Adds test snap to test_version_upgrades
  tests/integration/tests/test_version_upgrades.py
Labels: backport release-1.32

#1303 chore: (CVE fix) Bump golang.org/x/crypto to v0.35.0
  src/k8s/go.mod
  src/k8s/go.sum
Labels: backport release-1.32

#1311 test: Do not expect k8sd to be active after node removal
  tests/integration/tests/test_annotations.py
  tests/integration/tests/test_util/util.py
Labels: backport release-1.32

#1323 chore: Bump rawfile-localpv image
  docs/canonicalk8s/snap/howto/install/offline.md
  src/k8s/pkg/k8sd/features/localpv/chart.go
Labels: backport release-1.32

#1298 docs: Add charm patch notices for 1.32
  docs/canonicalk8s/charm/howto/upgrade-minor.md
  docs/canonicalk8s/charm/howto/upgrade-patch.md
  docs/canonicalk8s/charm/reference/versions/1.32.md
  docs/canonicalk8s/custom_conf.py
  docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
Labels: backport release-1.32

#1337 test: Remove mixed-version join test
  tests/integration/tests/test_clustering.py
Labels: backport release-1.32

#1280 feat: bump coredns version to 1.12, chart to 1.39.2
  build-scripts/hack/update-coredns-chart.sh
  k8s/manifests/charts/coredns-1.36.2.tgz
  k8s/manifests/charts/coredns-1.39.2.tgz
  src/k8s/pkg/k8sd/features/coredns/chart.go
  src/k8s/pkg/k8sd/features/coredns/coredns.go
Labels: dependencies, backport release-1.32, backport release-1.33

#1260 docs: update proxy.md
  docs/canonicalk8s/charm/howto/proxy.md
Labels: backport release-1.32, backport release-1.33

#1363 fix: update node label controller, allowing custom node names
  src/k8s/pkg/k8sd/app/app.go
  src/k8s/pkg/k8sd/controllers/node_label.go
  src/k8s/pkg/k8sd/controllers/node_label_test.go
Labels: backport release-1.32, backport release-1.33

#1375 fix: Retry Kubernetes node removal on an internal server error
  src/k8s/pkg/client/kubernetes/node.go
  src/k8s/pkg/client/kubernetes/node_test.go
Labels: backport release-1.32, backport release-1.33
