Repository canonical/k8s-snap, pull requests merged in 2025-05, with the labels that each got.

#1222 fix: Add quotations to service argument values to care for escape characters
  src/k8s/pkg/k8sd/setup/kubelet.go
  src/k8s/pkg/k8sd/setup/kubelet_test.go
  src/k8s/pkg/snap/util/arguments.go
  src/k8s/pkg/utils/file.go
  tests/integration/tests/test_config_propagation.py
  tests/integration/tests/test_smoke.py
Labels: backport release-1.32, backport release-1.33

#1385 fix: BOM generation outside of snapcraft
  build-scripts/generate-bom.py
Labels: backport release-1.32, backport release-1.33

#1299 docs: Add snap patch notices for 1.32
  docs/canonicalk8s/snap/reference/versions/1.32.md
  docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
Labels: backport release-1.32, backport release-1.33

#1370 fix: Properly parse IPv6 endpoints for k8s-apiserver-proxy.json
  src/k8s/pkg/client/kubernetes/endpoints.go
  src/k8s/pkg/proxy/endpoints.go
  src/k8s/pkg/utils/endpoints.go
  src/k8s/pkg/utils/endpoints_test.go
Labels: backport release-1.32, backport release-1.33

#1398 fix: Make backport conventional commit conformant
  .github/workflows/backport.yaml
Labels: backport release-1.33

#1395 test: Disable moonray testing for 1.33+
  .github/workflows/lint_and_integration.yaml
Labels: backport release-1.33

#1355 test: Skip CNCF Disruptive tests
  tests/integration/tests/test_cncf_conformace.py
Labels: backport release-1.32, backport release-1.33

#1411 docs: Fix indentation in CAPI reference page
  docs/canonicalk8s/capi/reference/configs.md
Labels: backport release-1.32, backport release-1.33

#1344 test: Fixes test_cilium_e2e test
  tests/integration/tests/test_cilium_e2e.py
Labels: backport release-1.32

#1416 docs: remove duplicate section in reference landing page
  docs/canonicalk8s/capi/reference/index.md
Labels: backport release-1.33

#1424 fix: Implement Revision for pebble
  src/k8s/pkg/snap/pebble.go
  src/k8s/pkg/snap/pebble_test.go
  src/k8s/pkg/snap/snap.go
Labels: backport release-1.32, backport release-1.33

#1425 fix: patch same upgrade status object
  src/k8s/pkg/k8sd/app/hooks_join.go
Labels: backport release-1.32, backport release-1.33

#1438 test: skip feature upgrades inplace early
  tests/integration/tests/test_version_upgrades.py
Labels: backport release-1.32, backport release-1.33

#1427 test: Sets default FLAVOR to classic
  tests/integration/tests/test_util/config.py
Labels: backport release-1.32, backport release-1.33

#1367 ci: Add dqlite deb source lists manually for TICS job
  tests/tics-scan.sh
Labels: backport release-1.32, backport release-1.33

#1444 feat: [release-1.33] Update component versions
  build-scripts/components/kubernetes/version
Labels: automerge

#1422 ci: Use official LXD setup workflow instead of workarounds
  .github/actions/install-lxd/action.yaml
  .github/workflows/build-snap.yaml
  .github/workflows/charm-e2e-tests.yaml
  .github/workflows/e2e-tests.yaml
  tests/integration/tests/test_util/util.py
Labels: backport release-1.32, backport release-1.33
